baseURL = "https://cryptomator.org/"
title = "Cryptomator"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableemoji = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
  [languages.de]
    weight = 2
    languageName = "Deutsch"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[module]

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-pro/webfonts"
    target = "static/webfonts"

  [[module.mounts]]
    source = "node_modules/jquery/dist"
    target = "assets/js/jquery"

  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/alpinejs"

  [[module.mounts]]
    source = "node_modules/lazysizes"
    target = "assets/js/lazysizes"

[markup.goldmark.renderer]
unsafe = true

[params]
  [params.releases]
    [params.releases.exe]
      version = "1.5.1"
      filename = "Cryptomator-1.5.1-x64.exe"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.5.1/Cryptomator-1.5.1-x64.exe"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.5.1/Cryptomator-1.5.1-x64.exe.asc"
      checksum = "ef7a11323b72c0576cf23d22057040faf63e459e7e13e76a7cf1d5a9e631386b"
    [params.releases.dmg]
      version = "1.5.1"
      filename = "Cryptomator-1.5.1.dmg"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.5.1/Cryptomator-1.5.1.dmg"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.5.1/Cryptomator-1.5.1.dmg.asc"
      checksum = "ec7e5ebe1f6221766ebc94d846edb36cfeef8ec32c026c09f1c988bbbd2b2d29"
    [params.releases.appimage]
      version = "1.5.1"
      filename = "cryptomator-1.5.1-x86_64.AppImage"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.5.1/cryptomator-1.5.1-x86_64.AppImage"
      signatureUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.5.1/cryptomator-1.5.1-x86_64.AppImage.asc"
      checksum = "774a135a4ed4d0dfc1021e4feab72118adf711fa4acdbb6207f75648d6658562"
    [params.releases.android]
      version = "1.5.2"
      filename = "Cryptomator-1.5.2.apk"
      downloadUrl = "https://static.cryptomator.org/android/1.5.2/Cryptomator-1.5.2.apk"
      checksum = "834ec1410e4ed0769ebffdd0d8f352661d429de8696d51217d170729a089b0b7"

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
