baseURL = "https://cryptomator.org/"
title = "Cryptomator"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableemoji = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
  [languages.de]
    weight = 2
    languageName = "Deutsch"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[module]

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-pro/webfonts"
    target = "static/webfonts"

  [[module.mounts]]
    source = "node_modules/jquery/dist"
    target = "assets/js/jquery"

  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/alpinejs"

  [[module.mounts]]
    source = "node_modules/lazysizes"
    target = "assets/js/lazysizes"

[markup.goldmark.renderer]
unsafe = true

[params]
  [params.releases]
    [params.releases.exe]
      version = "1.4.15"
      filename = "Cryptomator-1.4.15-x64.exe"
      downloadUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.4.15/Cryptomator-1.4.15-x64.exe"
      signatureUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.4.15/Cryptomator-1.4.15-x64.exe.asc"
      checksum = "e7618f0eba90012370d9ebc98e01496d5069728441e40d312aaab9316dc6a740"
    [params.releases.dmg]
      version = "1.4.17"
      filename = "Cryptomator-1.4.17.dmg"
      downloadUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.4.17/Cryptomator-1.4.17.dmg"
      signatureUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.4.17/Cryptomator-1.4.17.dmg.asc"
      checksum = "85d4ce3c022065d15411d31eb71029ee2f643af6ab34deb492b23bc9e0120298"
    [params.releases.appimage]
      version = "1.4.15"
      filename = "cryptomator-1.4.15-x86_64.AppImage"
      downloadUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.4.15/cryptomator-1.4.15-x86_64.AppImage"
      signatureUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.4.15/cryptomator-1.4.15-x86_64.AppImage.asc"
      checksum = "9d52051abc07727e2b6868e70347910d41347147078213e3ea846d26d113c047"
    [params.releases.android]
      version = "1.5.0-beta4"
      filename = "Cryptomator-1.5.0-beta4.apk"
      downloadUrl = "https://static.cryptomator.org/android/1.5.0-beta4/Cryptomator-1.5.0-beta4.apk"

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
