baseURL = "https://cryptomator.org/"
title = "Cryptomator"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableemoji = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
  [languages.de]
    weight = 2
    languageName = "Deutsch"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[module]

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-pro/webfonts"
    target = "static/webfonts"

  [[module.mounts]]
    source = "node_modules/jquery/dist"
    target = "assets/js/jquery"

  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/alpinejs"

  [[module.mounts]]
    source = "node_modules/lazysizes"
    target = "assets/js/lazysizes"

[markup.goldmark.renderer]
unsafe = true

[params]
  [params.releases]
    [params.releases.exe]
      version = "1.5.0-rc2"
      filename = "Cryptomator-1.5.0-rc2-x64.exe"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.5.0-rc2/Cryptomator-1.5.0-rc2-x64.exe"
      signatureUrl = "TODO"
      checksum = "TODO"
    [params.releases.dmg]
      version = "1.5.0-rc2"
      filename = "Cryptomator-1.5.0-rc2.dmg"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.5.0-rc2/Cryptomator-1.5.0-rc2.dmg"
      signatureUrl = "TODO"
      checksum = "TODO"
    [params.releases.appimage]
      version = "1.5.0-rc2"
      filename = "cryptomator-1.5.0-rc2-x86_64.AppImage"
      downloadUrl = "https://github.com/cryptomator/cryptomator/releases/download/1.5.0-rc2/cryptomator-1.5.0-rc2-x86_64.AppImage"
      signatureUrl = "TODO"
      checksum = "TODO"
    [params.releases.android]
      version = "1.5.0"
      filename = "Cryptomator-1.5.0.apk"
      downloadUrl = "https://static.cryptomator.org/android/1.5.0/Cryptomator-1.5.0.apk"
      checksum = "8b9f6c75e346fa1211ee18594aac8797cc279bc7571e85101d65fcfbe1841e43"

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
