baseURL = "https://cryptomator.org/"
title = "Cryptomator"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableemoji = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
  [languages.de]
    weight = 2
    languageName = "Deutsch"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[module]

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-pro/webfonts"
    target = "static/webfonts"

  [[module.mounts]]
    source = "node_modules/jquery/dist"
    target = "assets/js/jquery"

  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/alpinejs"

  [[module.mounts]]
    source = "node_modules/lazysizes"
    target = "assets/js/lazysizes"

[markup.goldmark.renderer]
unsafe = true

[params]
  [params.releases]
    [params.releases.exe]
      version = "1.5.4"
      filename = "Cryptomator-1.5.4-x64.exe"
      downloadUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.4/Cryptomator-1.5.4-x64.exe"
      signatureUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.4/Cryptomator-1.5.4-x64.exe.asc"
      checksum = "53413ff1b07358b5ca61cd81a9bbe4d25e4a960caf836e0a51d1edf83263c208"
    [params.releases.dmg]
      version = "1.5.4"
      filename = "Cryptomator-1.5.4.dmg"
      downloadUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.4/Cryptomator-1.5.4.dmg"
      signatureUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.4/Cryptomator-1.5.4.dmg.asc"
      checksum = "f9f2ba4136d9367cdedb509287734734aa9b132f5f48b1d960416ce4c3b6cc44"
    [params.releases.appimage]
      version = "1.5.4"
      filename = "cryptomator-1.5.4-x86_64.AppImage"
      downloadUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.4/cryptomator-1.5.4-x86_64.AppImage"
      signatureUrl = "https://dl.bintray.com/cryptomator/cryptomator/1.5.4/cryptomator-1.5.4-x86_64.AppImage.asc"
      checksum = "ab8152784b22c88f761f224f29c2ddf35113717517104be78ac511cf7686f7b1"
    [params.releases.android]
      version = "1.5.3"
      filename = "Cryptomator-1.5.3.apk"
      downloadUrl = "https://static.cryptomator.org/android/1.5.3/Cryptomator-1.5.3.apk"
      checksum = "ee58c49546f9695d26d5d8e0b818fd815ca57752b36b61d3150c65271823525b"

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
